### ISSUE TITLE
Nexus Issues and game crashes under certain circumstances

### ISSUE THREAD

**Issue by 8comimi** [SanAndreasP/ClaySoldiersMod#22] opened 2015-02-06 01:25 UTC
You may already know that there are problems with the nexus, but whenever I put something inside of it my game crashes and I can't load my world again without it crashing. Another thing is that when I have about a hundred or so clay soldiers spawned and they are all collecting items at once, my game will crash and continue to do so. I basically spawn in 80 soldiers, throw out a stack or two of leather, the game has no problem, a few seconds later it lags for a second and then crashes. I have fully updated java 7 and am on 1.7.10 with the latest forge update and clay soldiers update. If I need to copy the crash report here just tell me and I will do so. 
Edit: I apologize forgetting to label this a bug.

**Comment by SanAndreasP** [comment] 2015-02-07 09:13
Need logs

**Comment by 8comimi** [comment] 2015-02-07 18:24
I am no longer able to replicate the clay soldiers crashing the game in large numbers while gathering resources, although I was able to a few days ago. I'll have to keep testing, but here is the crash report cause every time I try to place something in a nexus.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/7/15 11:20 AM
Description: Rendering Block Entity

java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/client/ItemRenderHelper
	at de.sanandrew.mods.claysoldiers.client.render.tileentity.RenderClayNexus.renderSoldierItem(RenderClayNexus.java:115)
	at de.sanandrew.mods.claysoldiers.client.render.tileentity.RenderClayNexus.func_147500_a(RenderClayNexus.java:54)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.sanandrew.core.manpack.util.client.ItemRenderHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at de.sanandrew.mods.claysoldiers.client.render.tileentity.RenderClayNexus.renderSoldierItem(RenderClayNexus.java:115)
	at de.sanandrew.mods.claysoldiers.client.render.tileentity.RenderClayNexus.func_147500_a(RenderClayNexus.java:54)

-- Block Entity Details --
Details:
	Name: claysoldiers:nexus_te // de.sanandrew.mods.claysoldiers.tileentity.TileEntityClayNexus
	Block type: ID #165 (tile.claysoldiers:nexus // de.sanandrew.mods.claysoldiers.block.BlockClayNexus)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1158,4,1012), Chunk: (at 10,0,4 in -73,63; contains blocks -1168,0,1008 to -1153,255,1023), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Actual block type: ID #165 (tile.claysoldiers:nexus // de.sanandrew.mods.claysoldiers.block.BlockClayNexus)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['8comimi'/21, l='MpServer', x=-1154.50, y=5.62, z=1012.50]]
	Chunk stats: MultiplayerChunkCache: 618, 618
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1152,4,1015), Chunk: (at 0,0,7 in -72,63; contains blocks -1152,0,1008 to -1137,255,1023), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Level time: 349 game time, 349 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['8comimi'/21, l='MpServer', x=-1154.50, y=5.62, z=1012.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 180226632 bytes (171 MB) / 324317184 bytes (309 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	sapmanpack{2.3.0} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	claysoldiers{2.0.0b} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SanAndreasP** [comment] 2015-02-07 21:07
sapmanpack{2.3.0} SanAndreasPs Manager Pack CORE edition Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
claysoldiers{2.0.0b} Clay Soldiers Mod Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

Old versions in place here. That crash was fixed recently.

Since you can't reproduce the issue anymore (I assume you've updated), I'll close this down now. Feel free to reopen it if you can replicate it.

**Closed by SanAndreasP** 2015-02-07 21:07 UTC
Labels: need logs
