### ISSUE TITLE
Im having problems and need help!

### ISSUE THREAD

**Issue by ChilledSniper** [SanAndreasP/ClaySoldiersMod#152] opened 2016-01-22 01:53 UTC
I downloaded the mod and the manager pack. I dragged the mod into the mod folder but when I started my forge its saying I need the manager pack, minimal version 2.4, and I have version 2.44. What do I need to do?

**Comment by Spartan322** [comment] 2016-01-22 02:21
probably duplicate of #148 
probably should keep discussion of similar problems in the same issue
Also next time provide the entire log (using either pastebin or gist please), just stating the last thing you saw on the log doesn't help at all.

**Comment by SanAndreasP** [comment] 2016-01-23 08:38
What @Spartan322 said.
We need the fml-client-latest.log from your /logs folder. Use https://gist.github.com to post it and give us the resulting link.

**Comment by beast98001** [comment] 2016-03-19 18:28
I Need Help When I tried To Make The Clay Soliders Build Houses They Wont And My Nexus Looks Diffrent From Other People That I looked Up On Youtube.

**Comment by beast98001** [comment] 2016-03-19 18:30
@SanAndreasP Forgot to tag your name but the info to what my problem is in this chat

**Comment by Spartan322** [comment] 2016-03-19 19:53
@beast98001 First, please don't hijack issues, next, #17, lastly, that last one isn't a problem, and probably shouldn't really be addressed, but there was a rewrite when SanAndreasP took on the project, which has been stated multiple times, also, whether this problem is a duplicate or not, its been waited on for too long without a response and should be closed, @SanAndreasP you should probably close this.

**Comment by SanAndreasP** [comment] 2016-06-28 08:59
Since there's no log for like 3 months now, I'm closing this.

~PS: cleaning out the issues now~

**Closed by SanAndreasP** 2016-06-28 08:59 UTC
