### ISSUE TITLE
Geko Bug 

### ISSUE THREAD

**Issue by Potshott** [SanAndreasP/ClaySoldiersMod#238] opened 2018-10-14 13:15 UTC
When a clay soldier is riding a geko and the geko spins on a stair while jumping with a block over it the clay soldier takes damage

**Comment by Potshott** [comment] 2018-10-14 13:16
Also clay soldiers who are riding rabbit barely move

**Comment by SanAndreasP** [comment] 2019-01-02 15:20
I consider this a duplicate of #241 (even if this issue is technically younger)

**Closed by SanAndreasP** 2019-01-02 15:20 UTC

**Comment by Potshott** [comment] 2019-01-11 19:20
ok
